export type { RepoFileSource, AnalysisProfile, Framework } from "./types.ts";
export { LocalDirFileSource } from "./file-source.ts";
export { analyze } from "./analyze.ts";
export type { ImportGraph, ImportGraphNode, ImportGraphEdge } from "./import-graph.ts";
export { buildImportGraph, renderGraphMd } from "./import-graph.ts";
export type { ConventionFinding, ConventionsReport, LintConfig } from "./detect/conventions.ts";
export { analyzeConventions, RULE_THRESHOLD } from "./detect/conventions.ts";
export type { ArchitectureInput, NarrationSections } from "./architecture.ts";
export { renderArchitectureMd, sanitizeNarration, SYSTEM_MAP_REGION_ID, SYSTEM_MAP_REGION_VERSION } from "./architecture.ts";
export { packRepo, estTokens, type RepoDigest } from "./pack-repo.ts";
export { auditRepo, buildAuditPrompt, type AuditFacts, type AuditOptions, type AuditConfig } from "./ai-audit.ts";
export { renderArchitectureDoc } from "./architecture.ts";
export type { NarrateConfig, NarrationInput } from "./ai-narrate.ts";
export { narrateArchitecture, pickSamples } from "./ai-narrate.ts";
export type { DesignToken, DesignTokensReport } from "./detect/design-tokens.ts";
export { analyzeDesignTokens } from "./detect/design-tokens.ts";
export type { DesignInput, DesignNarration } from "./design.ts";
export { renderDesignMd, DESIGN_REGION_ID, DESIGN_REGION_VERSION } from "./design.ts";
export type { DesignNarrationInput } from "./ai-narrate.ts";
export { narrateDesign, pickDesignSamples } from "./ai-narrate.ts";
