import {
  ENTRY_FILES,
  isEntryFile,
  mergeManagedRegion,
  renderPack,
  renderRepoFileUnion,
  renderRolloutFiles,
  stripManagedRegion,
  strippedManagedPackIds,
  type FileMap,
  type RolloutFiles,
  type WorkflowPack,
} from "@baselane/packs";
import { GithubApiError, type GithubClient } from "./github.ts";

export interface Distribution {
  branch: string;
  title: string;
  body: string;
  files: Record<string, string>;
}

/** Context for resolving what an ENTRY file's committed content should be — the caller
 * either has a better answer already (e.g. an admin-approved AdoptionRec's merged content)
 * or leaves it to the default read-existing-then-merge below. Returning undefined means
 * "no override, use the default merge for this path". */
export interface ResolveEntryContentCtx {
  path: string;
  managedBody: string;
  packId: string;
  version: string;
}
export type ResolveEntryContent = (ctx: ResolveEntryContentCtx) => Promise<string | undefined> | string | undefined;

export interface DistributePackOptions {
  /** Optional override for ENTRY files (isEntryFile), e.g. the portal passing an approved
   * AdoptionRec's already-reviewed merged content. Fully-generated files are never routed
   * through this — they always commit the rendered content as-is. */
  resolveEntryContent?: ResolveEntryContent;
}

export function buildDistribution(pack: WorkflowPack): Distribution {
  const files = renderPack(pack);
  const fileList = Object.keys(files)
    .sort()
    .map((f) => `- \`${f}\``)
    .join("\n");
  return {
    branch: `baselane/${pack.id}`,
    title: `chore: adopt baselane pack ${pack.id} v${pack.version}`,
    body: [
      `Adopts the **${pack.title}** workflow pack (\`${pack.id}\` v${pack.version}).`,
      "",
      pack.summary,
      "",
      "Files:",
      fileList,
      "",
      "Generated by baselane — https://baselane.dev",
    ].join("\n"),
    files,
  };
}

export async function distributePack(
  gh: GithubClient,
  repoRef: string,
  pack: WorkflowPack,
  opts: DistributePackOptions = {},
): Promise<{ prUrl: string; branch: string; fileCount: number }> {
  const m = /^([^/\s]+)\/([^/\s]+)$/.exec(repoRef);
  if (!m) throw new Error(`repo must be owner/repo, got: ${repoRef}`);
  const [, owner, repo] = m;

  const dist = buildDistribution(pack);

  const { defaultBranch } = await gh.getRepo(owner, repo);
  const baseSha = await gh.getRefSha(owner, repo, defaultBranch);
  try {
    await gh.createBranch(owner, repo, dist.branch, baseSha);
  } catch (err) {
    if (err instanceof GithubApiError && err.status === 422) {
      throw new Error(`branch ${dist.branch} already exists — close or delete the previous baselane PR first`);
    }
    throw err;
  }

  // For ENTRY files (AGENTS.md/CLAUDE.md/...) the repo may already have its own
  // project-specific content — never wholesale-replace it. Read what's on the default
  // branch today and merge baselane's managed region into it, unless the caller already
  // has a better answer (an approved AdoptionRec's reviewed merge).
  async function defaultMerge(ctx: ResolveEntryContentCtx): Promise<string> {
    const existing = await gh.getFileContent(owner, repo, ctx.path, defaultBranch);
    return mergeManagedRegion(existing, ctx.managedBody, ctx.packId, ctx.version);
  }

  // #16: the branch already exists on GitHub now. If committing files or opening the PR fails
  // partway, delete it so it isn't stranded — otherwise the deterministic branch name makes the
  // NEXT attempt 422 with a "close the previous PR first" message when no PR was ever created,
  // blocking retry. Cleanup is best-effort: a failure deleting the branch must not mask the
  // original error that caused us to bail.
  const paths = Object.keys(dist.files).sort();
  try {
    for (const path of paths) {
      const managedBody = dist.files[path];
      let content = managedBody;
      if (isEntryFile(path)) {
        const ctx: ResolveEntryContentCtx = { path, managedBody, packId: pack.id, version: pack.version };
        content = (await opts.resolveEntryContent?.(ctx)) ?? (await defaultMerge(ctx));
      }
      const sha = await gh.getFileSha(owner, repo, path, defaultBranch);
      await gh.putFile(owner, repo, path, {
        branch: dist.branch,
        message: `chore: baselane ${pack.id} v${pack.version} — ${path}`,
        content,
        sha,
      });
    }

    const pr = await gh.createPullRequest(owner, repo, {
      title: dist.title,
      body: dist.body,
      head: dist.branch,
      base: defaultBranch,
    });
    return { prUrl: pr.url, branch: dist.branch, fileCount: paths.length };
  } catch (err) {
    await gh.deleteBranch(owner, repo, dist.branch).catch(() => {});
    throw err;
  }
}

const ROLLOUT_BRANCH = "baselane/rollout";

/** Committed alongside every other rollout file — the authoritative record of which paths
 * baselane itself wrote on THIS rollout. The next rollout reads it back to scope orphan
 * deletion to paths baselane actually authored, never to a client's own `.claude/` content
 * that happens to live on the same branch (see distributeRollout's delete step). */
const ROLLOUT_MANIFEST_PATH = ".baselane/rollout-manifest.json";

interface RolloutManifest {
  version: 1;
  paths: string[];
}

function buildRolloutManifest(files: FileMap): string {
  const manifest: RolloutManifest = { version: 1, paths: Object.keys(files).sort() };
  return JSON.stringify(manifest, null, 2) + "\n";
}

/** Empty on any absence/malformation (missing file, bad JSON, non-array `paths`, non-string
 * entries) — a first-ever rollout (or a corrupted manifest) must delete nothing rather than
 * guess. */
function parseRolloutManifestPaths(raw: string | null): string[] {
  if (raw === null) return [];
  try {
    const parsed = JSON.parse(raw) as { paths?: unknown };
    if (!Array.isArray(parsed.paths) || !parsed.paths.every((p) => typeof p === "string")) return [];
    return parsed.paths as string[];
  } catch {
    return [];
  }
}

/**
 * A per-repo artifact the platform computed centrally (system-map, graph, wiki seed, …) and folds
 * into the rollout PR so a repo lands populated, not with a "compute it yourself" scaffold — see
 * docs/superpowers/specs/2026-07-11-central-compute-push.md and -central-compute-push-seed-design.md.
 *
 * A `region` artifact (ARCHITECTURE.md, DESIGN.md) re-merges its `managedBody` into the named managed
 * region against the branch's CURRENT content — prose outside the region is preserved, and the
 * generate-time preview is never committed. A `file` artifact (a generated `.baselane/graph.json` or
 * a seed `.baselane/wiki/*.md`) is committed verbatim.
 */
export type ComputedArtifact =
  | { path: string; managedBody: string; regionId: string; regionVersion: string }
  | { path: string; content: string };

export interface DistributeRolloutOptions {
  /** Same override hook as DistributePackOptions, applied per (path, pack) fold step: when it
   * answers for a pack's contribution to an entry file, that answer replaces the mechanical
   * merge for that pack — later packs in the ordered set still fold in normally on top of it. */
  resolveEntryContent?: ResolveEntryContent;
  /** Centrally-computed per-repo artifacts folded into the rollout after the pack files are built. */
  computedArtifacts?: ComputedArtifact[];
}

export type DistributeRolloutResult =
  | { prUrl: string; branch: typeof ROLLOUT_BRANCH; fileCount: number; collisions: string[] }
  | { closed: true };

async function ensureRolloutBranch(gh: GithubClient, owner: string, repo: string, defaultBranch: string): Promise<void> {
  try {
    await gh.getRefSha(owner, repo, ROLLOUT_BRANCH);
  } catch (err) {
    if (!(err instanceof GithubApiError) || err.status !== 404) throw err;
    const baseSha = await gh.getRefSha(owner, repo, defaultBranch);
    await gh.createBranch(owner, repo, ROLLOUT_BRANCH, baseSha);
  }
}

async function closeRollout(gh: GithubClient, owner: string, repo: string): Promise<{ closed: true }> {
  const open = await gh.listOpenPullRequests(owner, repo);
  for (const pr of open.filter((p) => p.headRef === ROLLOUT_BRANCH)) {
    await gh.closePullRequest(owner, repo, pr.number);
  }
  try {
    await gh.deleteBranch(owner, repo, ROLLOUT_BRANCH);
  } catch {
    // branch may already be gone
  }
  return { closed: true };
}

/** Computes the rollout branch's full file set. With no `resolveEntryContent`, delegates straight
 * to the pure `renderRolloutFiles` after fetching each entry path's default-branch content. With
 * one, re-runs the entry-file fold here (async-aware) so an approved review can still win per
 * (path, pack), then reuses `renderRepoFileUnion` for everything else exactly as `renderRolloutFiles`
 * would. */
/** Folds any centrally-computed artifacts onto the base rollout file set, content-preservingly:
 * a `region` artifact re-merges its managed region against the branch's current content; a `file`
 * artifact commits verbatim. No artifacts ⇒ the base set is returned untouched (no extra fetches). */
async function computeRolloutFiles(
  gh: GithubClient,
  owner: string,
  repo: string,
  defaultBranch: string,
  packs: WorkflowPack[],
  opts: DistributeRolloutOptions,
): Promise<RolloutFiles> {
  const base = await computeBaseRolloutFiles(gh, owner, repo, defaultBranch, packs, opts);
  const artifacts = opts.computedArtifacts ?? [];
  const files: FileMap = { ...base.files };
  for (const art of artifacts) {
    if ("content" in art) {
      files[art.path] = art.content;
    } else {
      const current = await gh.getFileContent(owner, repo, art.path, defaultBranch);
      files[art.path] = mergeManagedRegion(current, art.managedBody, art.regionId, art.regionVersion);
    }
  }
  // Recorded AFTER every other produced path is known (packs + computed artifacts), and never
  // lists itself — this is what the NEXT rollout trusts as "paths baselane authored".
  files[ROLLOUT_MANIFEST_PATH] = buildRolloutManifest(files);
  return { files, collisions: base.collisions };
}

async function computeBaseRolloutFiles(
  gh: GithubClient,
  owner: string,
  repo: string,
  defaultBranch: string,
  packs: WorkflowPack[],
  opts: DistributeRolloutOptions,
): Promise<RolloutFiles> {
  if (!opts.resolveEntryContent) {
    const baseEntryFiles: Record<string, string | null> = {};
    for (const path of ENTRY_FILES) {
      baseEntryFiles[path] = await gh.getFileContent(owner, repo, path, defaultBranch);
    }
    return renderRolloutFiles(baseEntryFiles, packs);
  }

  const entryFiles: FileMap = {};
  const wantedIds = new Set(packs.map((p) => p.id));
  const rendered = packs.map((pack) => ({ pack, body: renderPack(pack) }));
  for (const path of ENTRY_FILES) {
    let content = await gh.getFileContent(owner, repo, path, defaultBranch);
    if (content !== null) {
      for (const packId of strippedManagedPackIds(content)) {
        if (!wantedIds.has(packId)) content = stripManagedRegion(content, packId);
      }
    }
    for (const { pack, body } of rendered) {
      const managedBody = body[path];
      if (managedBody === undefined) continue;
      const ctx: ResolveEntryContentCtx = { path, managedBody, packId: pack.id, version: pack.version };
      const override = await opts.resolveEntryContent(ctx);
      content = override ?? mergeManagedRegion(content, managedBody, pack.id, pack.version);
    }
    if (content !== null) entryFiles[path] = content;
  }
  const { files: repoFiles, collisions } = renderRepoFileUnion(packs);
  return { files: { ...entryFiles, ...repoFiles }, collisions };
}

/**
 * Distributes an ordered (most-specific-first) effective pack set to ONE combined
 * `baselane/rollout` branch/PR per repo — see docs/superpowers/specs/2026-07-11-union-rollout-pr.md.
 * An empty `packs` closes the existing rollout PR and deletes its branch instead. Unchanged
 * files (same content already on the branch) are skipped — no empty commits.
 */
export async function distributeRollout(
  gh: GithubClient,
  repoRef: string,
  packs: WorkflowPack[],
  opts: DistributeRolloutOptions = {},
): Promise<DistributeRolloutResult> {
  const m = /^([^/\s]+)\/([^/\s]+)$/.exec(repoRef);
  if (!m) throw new Error(`repo must be owner/repo, got: ${repoRef}`);
  const [, owner, repo] = m;

  if (packs.length === 0) return closeRollout(gh, owner, repo);

  const { defaultBranch } = await gh.getRepo(owner, repo);
  await ensureRolloutBranch(gh, owner, repo, defaultBranch);

  const rollout = await computeRolloutFiles(gh, owner, repo, defaultBranch, packs, opts);

  // Read the PRIOR rollout's manifest before the add loop below can commit THIS run's fresh
  // manifest over it — orphan deletion (further down) needs the OLD list of paths baselane
  // itself wrote on the last rollout, never derived from the branch's actual tree. The rollout
  // branch is cut from the repo's default branch (ensureRolloutBranch), so a client's own
  // `.claude/skills/foo/SKILL.md` — which baselane never wrote — can live there too; deriving
  // orphans from the tree would delete it. No prior manifest (first-ever rollout, or one that
  // failed to parse) means nothing is deleted.
  const priorManifestRaw = await gh.getFileContent(owner, repo, ROLLOUT_MANIFEST_PATH, ROLLOUT_BRANCH);
  const priorPaths = parseRolloutManifestPaths(priorManifestRaw);

  let fileCount = 0;
  for (const path of Object.keys(rollout.files).sort()) {
    const newContent = rollout.files[path];
    const existing = await gh.getFileContent(owner, repo, path, ROLLOUT_BRANCH);
    if (existing === newContent) continue;
    const sha = await gh.getFileSha(owner, repo, path, ROLLOUT_BRANCH);
    await gh.putFile(owner, repo, path, {
      branch: ROLLOUT_BRANCH,
      message: `chore: baselane rollout — ${path}`,
      content: newContent,
      sha,
    });
    fileCount++;
  }

  // The add loop above is add-only: a pack dropped from the effective set stops appearing in
  // rollout.files, but its uniquely-contributed paths (.claude/agents/*.md, .claude/commands/*.md,
  // .claude/skills/**, .baselane/* capability companions, even a now-empty ENTRY_FILES entry)
  // would otherwise linger on the branch forever. `isBaselaneManagedPath` is kept as a defensive
  // secondary guard on top of the manifest scoping above.
  const isBaselaneManagedPath = (path: string): boolean =>
    path.startsWith(".claude/") || path.startsWith(".baselane/") || (ENTRY_FILES as readonly string[]).includes(path);
  const orphans = priorPaths
    .filter((path) => path !== ROLLOUT_MANIFEST_PATH && isBaselaneManagedPath(path) && !(path in rollout.files))
    .sort();
  for (const path of orphans) {
    const sha = await gh.getFileSha(owner, repo, path, ROLLOUT_BRANCH);
    if (sha === null) continue; // already gone from the branch — nothing to delete
    await gh.deleteFile(owner, repo, path, {
      branch: ROLLOUT_BRANCH,
      message: `chore: baselane rollout — remove ${path}`,
      sha,
    });
    fileCount++;
  }

  const open = await gh.listOpenPullRequests(owner, repo);
  const existingPr = open.find((p) => p.headRef === ROLLOUT_BRANCH);
  if (existingPr) return { prUrl: existingPr.url, branch: ROLLOUT_BRANCH, fileCount, collisions: rollout.collisions };

  const packList = packs.map((p) => `- **${p.title}** (\`${p.id}\` v${p.version})`).join("\n");
  const fileList = Object.keys(rollout.files).sort().map((f) => `- \`${f}\``).join("\n");
  const body = [
    "Adopts baselane's combined rollout of:",
    "",
    packList,
    "",
    "Files:",
    fileList,
    ...(rollout.collisions.length > 0 ? ["", `Collisions (first-writer-wins, review before merge): ${rollout.collisions.join(", ")}`] : []),
    "",
    "Generated by baselane — https://baselane.dev",
  ].join("\n");
  const pr = await gh.createPullRequest(owner, repo, {
    title: "chore: adopt baselane workflow packs",
    body,
    head: ROLLOUT_BRANCH,
    base: defaultBranch,
  });
  return { prUrl: pr.url, branch: ROLLOUT_BRANCH, fileCount, collisions: rollout.collisions };
}
