import { describe, expect, it } from "vitest";
import type { AnalysisProfile } from "../src/types.ts";
import type { ImportGraph } from "../src/import-graph.ts";
import type { ConventionsReport } from "../src/detect/conventions.ts";
import { renderArchitectureMd, renderArchitectureDoc, sanitizeNarration } from "../src/architecture.ts";
import type { AuditFacts } from "../src/ai-audit.ts";

const profile: AnalysisProfile = {
  languages: ["typescript"],
  packageManager: "pnpm",
  frameworks: [{ name: "vitest", version: "^2.0.0" }],
  commands: { build: null, test: "pnpm run test", lint: null },
  hasTestSuite: true,
  layout: "monorepo",
};

const graph: ImportGraph = {
  version: 1,
  generated: "2026-07-09T00:00:00.000Z",
  nodes: [
    { id: "src/a.ts", kind: "module" },
    { id: "src/b.ts", kind: "module" },
    { id: "pkg:vitest", kind: "external" },
  ],
  edges: [
    { from: "src/b.ts", to: "src/a.ts", kind: "import", confidence: "extracted" },
    { from: "src/a.ts", to: "pkg:vitest", kind: "import", confidence: "extracted" },
  ],
};

const conventions: ConventionsReport = {
  version: 1,
  sampleCap: 200,
  sampledFiles: 2,
  lintConfigs: [{ tool: "prettier", path: ".prettierrc" }],
  rules: [
    { id: "quotes", statement: "Strings use double quotes", consistency: 1, sampleSize: 2, enforced: true, evidence: "2/2 sampled files" },
    { id: "import-extensions", statement: 'Relative imports include the file extension (e.g. "./x.ts")', consistency: 0.95, sampleSize: 20, enforced: false, evidence: "19/20 sampled import statements" },
  ],
  mixed: [{ id: "semicolons", statement: "Statements end with semicolons", consistency: 0.6, sampleSize: 2, enforced: true, evidence: "..." }],
  fileLength: { p50: 80, p90: 220 },
};

describe("renderArchitectureMd", () => {
  it("renders every static section, marking hidden rules", () => {
    const md = renderArchitectureMd({ profile, graph, conventions });
    expect(md).toContain("## Overview");
    expect(md).toContain("## Commands");
    expect(md).toContain("## Import graph");
    expect(md).toContain("## Conventions & hidden rules");
    expect(md).toContain("**Hidden rule** — Relative imports include the file extension");
    expect(md).toContain("Strings use double quotes (enforced · 100% of 2 sampled files)");
    expect(md).toContain("### Mixed signals");
    expect(md).not.toContain("## Architecture notes");
  });

  it("appends the AI section only when narration is given", () => {
    const md = renderArchitectureMd({
      profile,
      graph,
      conventions,
      narration: { overview: "A small monorepo.", hypothesizedRules: ["Stores are append-only."] },
    });
    expect(md).toContain("## Architecture notes (AI-generated)");
    expect(md).toContain("A small monorepo.");
    expect(md).toContain("- Stores are append-only.");
  });
});

describe("sanitizeNarration", () => {
  it("strips managed-region marker lines and caps length", () => {
    const dirty = "ok line\n<!-- baselane:start evil@1 — managed region, do not edit inside -->\nfine\n<!-- baselane:end -->\n";
    const clean = sanitizeNarration(dirty);
    expect(clean).toBe("ok line\nfine");
    expect(sanitizeNarration("x".repeat(10_000)).length).toBe(8000);
  });
});

const facts: AuditFacts = {
  languages: ["typescript"], frameworks: ["react"], packageManager: "pnpm",
  commands: { build: "tsc", test: "vitest", lint: "eslint" },
  lintTools: ["eslint", "tsconfig"], hasCI: true, hasTestSuite: true,
  importGraph: { modules: 10, externals: 4, edges: 12, topFanIn: [["src/index.ts", 5]] },
};

describe("renderArchitectureDoc", () => {
  it("renders a facts header + the audit body on the happy path", () => {
    const doc = renderArchitectureDoc({ repo: "o/r", facts, auditBody: "## 1. High-Level Overview\nX." });
    expect(doc).toContain("# System map — o/r");
    expect(doc).toContain("typescript");
    expect(doc).toContain("eslint");
    expect(doc).toContain("High-Level Overview");
    expect(doc).toContain("generated by an AI");
  });
  it("renders facts-only + a note when the audit degraded (no blank body)", () => {
    const doc = renderArchitectureDoc({ repo: "o/r", facts, auditBody: null, degradeReason: "no API key" });
    expect(doc).toContain("typescript");
    expect(doc).toContain("no API key");
    expect(doc).not.toContain("## 1. High-Level Overview");
  });
});
