// Builds the self-contained `baselane-agent` binary for the HOST platform via
// Node's Single Executable Application support (https://nodejs.org/api/single-executable-applications.html).
//
// Zero new checked-in dependencies, by design:
//   1. the repo's existing `typescript` dev-dep transpiles each agent source to CommonJS,
//   2. this script stitches them into ONE .cjs file with a ~20-line module registry
//      (possible because the agent only imports node: builtins + flat relative "./x.ts"),
//   3. `node --experimental-sea-config` produces the SEA blob,
//   4. `postject` (fetched on demand with `pnpm dlx`, never added to package.json)
//      injects the blob into a copy of the running node binary,
//   5. on macOS the copy is ad-hoc re-signed (unsigned arm64 binaries won't exec).
//
// Usage: node apps/agent/scripts/build-sea.mjs   (from anywhere; paths are self-anchored)
// Output: apps/agent/dist/baselane-agent

import { execFileSync } from "node:child_process";
import { chmodSync, copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const agentDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(agentDir, "src");
const buildDir = join(agentDir, "build");
const distDir = join(agentDir, "dist");
const ENTRY = "cli.ts";

// ---- 1. collect the transitive import graph from the CLI entry (flat src dir) ----
function importsOf(source) {
  const found = [];
  const re = /from\s+"(\.\/[A-Za-z0-9._-]+\.ts)"/g;
  for (let m; (m = re.exec(source)); ) found.push(m[1].slice(2));
  return found;
}

const modules = new Map(); // key "x.ts" -> transpiled CJS source
const queue = [ENTRY];
while (queue.length > 0) {
  const key = queue.shift();
  if (modules.has(key)) continue;
  const source = readFileSync(join(srcDir, key), "utf8");
  const out = ts.transpileModule(source, {
    fileName: key,
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true },
  });
  modules.set(key, out.outputText);
  queue.push(...importsOf(source));
}

// ---- 2. emit one CJS file: module registry + loader + entry ----
const parts = [
  "// GENERATED by apps/agent/scripts/build-sea.mjs — do not edit.",
  '"use strict";',
  "const __defs = Object.create(null);",
  "const __cache = Object.create(null);",
  "function __load(key) {",
  "  if (__cache[key]) return __cache[key].exports;",
  "  const def = __defs[key];",
  '  if (!def) throw new Error("bundled module not found: " + key);',
  "  const mod = (__cache[key] = { exports: {} });",
  "  def(mod, mod.exports, (spec) => {",
  '    if (!spec.startsWith("./")) return require(spec); // node: builtins only',
  "    return __load(spec.slice(2));",
  "  });",
  "  return mod.exports;",
  "}",
];
for (const [key, code] of modules) {
  parts.push(`__defs[${JSON.stringify(key)}] = function (module, exports, require) {`, code, "};");
}
parts.push(
  `__load(${JSON.stringify(ENTRY)}).main(process.argv.slice(2)).then(`,
  "  (code) => process.exit(code),",
  "  (err) => { console.error(err instanceof Error ? err.message : String(err)); process.exit(1); },",
  ");",
);

mkdirSync(buildDir, { recursive: true });
mkdirSync(distDir, { recursive: true });
writeFileSync(join(buildDir, "agent-sea.cjs"), parts.join("\n"));
console.log(`bundled ${modules.size} modules -> build/agent-sea.cjs`);

// ---- 3. SEA blob (sea-config.json is committed next to package.json) ----
execFileSync(process.execPath, ["--experimental-sea-config", "sea-config.json"], { cwd: agentDir, stdio: "inherit" });

// ---- 4. copy node + inject the blob (postject via pnpm dlx — not a package.json dep) ----
const binary = join(distDir, "baselane-agent");
rmSync(binary, { force: true }); // a previous run's copy is 0555 (node ships read-only)
copyFileSync(process.execPath, binary);
chmodSync(binary, 0o755); // postject must be able to write the blob into it
if (process.platform === "darwin") execFileSync("codesign", ["--remove-signature", binary]);
const postjectArgs = [
  "postject", binary, "NODE_SEA_BLOB", join(buildDir, "sea-prep.blob"),
  "--sentinel-fuse", "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2",
  ...(process.platform === "darwin" ? ["--macho-segment-name", "NODE_SEA"] : []),
];
execFileSync("pnpm", ["dlx", ...postjectArgs], { stdio: "inherit" });
if (process.platform === "darwin") execFileSync("codesign", ["--sign", "-", binary]);

// ---- 5. smoke: no args must print usage and exit 1 ----
let usage = "";
try {
  execFileSync(binary, [], { stdio: "pipe" });
  console.error("SMOKE FAIL: expected exit 1 with usage");
  process.exit(1);
} catch (err) {
  usage = String(err.stderr ?? "");
  if (!usage.includes("usage: baselane-agent sync")) {
    console.error(`SMOKE FAIL: usage text missing, got: ${usage.slice(0, 200)}`);
    process.exit(1);
  }
}
console.log(`SMOKE PASS: dist/baselane-agent prints usage (${process.platform}-${process.arch})`);

// ---- 6. drop a copy where Tauri's externalBin expects the sidecar ----
// (see apps/desktop/src-tauri/tauri.conf.json — bundler resolves binaries/baselane-agent-<host triple>)
const TRIPLES = {
  "darwin-arm64": "aarch64-apple-darwin",
  "darwin-x64": "x86_64-apple-darwin",
  "linux-x64": "x86_64-unknown-linux-gnu",
  "linux-arm64": "aarch64-unknown-linux-gnu",
  "win32-x64": "x86_64-pc-windows-msvc",
};
const triple = TRIPLES[`${process.platform}-${process.arch}`];
if (triple) {
  const sidecarDir = resolve(agentDir, "..", "desktop", "src-tauri", "binaries");
  mkdirSync(sidecarDir, { recursive: true });
  const ext = process.platform === "win32" ? ".exe" : "";
  const sidecar = join(sidecarDir, `baselane-agent-${triple}${ext}`);
  rmSync(sidecar, { force: true });
  copyFileSync(binary, sidecar);
  chmodSync(sidecar, 0o755);
  console.log(`sidecar staged: apps/desktop/src-tauri/binaries/baselane-agent-${triple}${ext}`);
} else {
  console.log(`NOTE: unknown platform ${process.platform}-${process.arch} — sidecar not staged for Tauri`);
}
