import type { Capability, FileMap, PackHook, WorkflowPack } from "../types.ts";

// Methods that render real scaffolding today. `treesitter` and `embeddings` intentionally have
// no adapter yet — unlike graphify/aider/lsp/sourcegraph, there is no canonical local
// tree-sitter-symbols tool or embeddings-search tool wired up here yet, so both stay an honest
// "coming soon" (via render/capabilities.ts's generic fallback) rather than a fabricated one.
const REAL_METHODS = new Set(["imports", "graphify", "aider", "lsp", "sourcegraph"]);

/** `.baselane/graph/README.md` (repo) / `graph/README.md` (bundle) — the `imports` method protocol. */
const GRAPH_README = `# Graph protocol (method: imports)

A queryable map of this repo's module dependencies, generated by lexical import scanning — so an
agent can answer "what imports this" / "what does this import" from a file instead of guessing
from grep.

## Schema

\`\`\`json
{
  "version": 1,
  "generated": "<ISO 8601 timestamp>",
  "nodes": [
    { "id": "<repo-relative-posix-path>", "kind": "module", "language": "<optional>" },
    { "id": "pkg:<name>", "kind": "external" }
  ],
  "edges": [
    { "from": "<node id>", "to": "<node id>", "kind": "import", "confidence": "extracted" }
  ]
}
\`\`\`

\`edges[].kind\` is one of \`import\`, \`require\`, or \`export-from\`.

## The query-before-grep rule

Before cross-module or refactoring work, consult \`.baselane/graph.json\` (or the human-readable
\`.baselane/graph/GRAPH.md\`) to answer what imports a file or what a file imports — do not reach
for grep first. The graph is generated from real import/require/export statements, so it is
authoritative for that question; grep is not (it also matches comments, strings, and unrelated
substrings).

## Regenerating

Run \`baselane graph .\` from the repo root whenever modules are added, removed, or moved. This
overwrites \`.baselane/graph.json\` and \`.baselane/graph/GRAPH.md\` in place — commit the refreshed
files alongside the change that caused them to go stale.

## Extracted vs inferred

Every edge here has \`confidence: "extracted"\` — it came from a direct lexical match, never a
guess. A future \`confidence: "inferred"\` tier is reserved for LLM-based enrichment (e.g. a
dependency that only shows up through dynamic dispatch); nothing in this repo fabricates an
inferred edge today.
`;

const GRAPH_COMMAND = {
  name: "graph",
  description: "Query the module dependency graph, or regenerate it after moving/adding modules.",
  argument_hint: '<module path to query | "regenerate">',
  prompt:
    "Follow the graph protocol in `.baselane/graph/README.md` for $ARGUMENTS. If this is a " +
    "lookup, read `.baselane/graph.json` (or `.baselane/graph/GRAPH.md`) to answer what imports " +
    "$ARGUMENTS or what $ARGUMENTS imports — do not grep for it. If $ARGUMENTS is " +
    '"regenerate" (or modules were just added, removed, or moved), run `baselane graph .` from ' +
    "the repo root and commit the refreshed `.baselane/graph.json` and `.baselane/graph/GRAPH.md`.",
};

const GRAPH_STOP_HOOK: PackHook = {
  event: "Stop",
  matcher: "",
  description: "Reminds the agent to regenerate the graph after adding or moving modules.",
  action: "print-reminder",
  message:
    "Before finishing, if you added, removed, or moved modules, regenerate the graph " +
    "(`baselane graph .` for the imports method, or your configured adapter's own step) — " +
    "see .baselane/graph/README.md.",
};

const GRAPHIFY_HOOK: PackHook = {
  event: "SessionStart",
  matcher: "",
  description: "Regenerates the graphify graph if the tool is installed; otherwise points at setup docs.",
  action: "run-command",
  command:
    'command -v graphify >/dev/null 2>&1 && graphify build . || echo "graphify not installed — ' +
    'see .baselane/graph/graphify/README.md for setup"',
};

/** The AGENTS.md capabilities-section note for a graph capability, regardless of store or method. */
export const GRAPH_AGENTS_NOTE =
  "### Graph\n\n" +
  "`.baselane/graph.json` / `.baselane/graph/GRAPH.md` is a generated module-dependency graph — " +
  "consult it before cross-module or refactoring work instead of grepping, and regenerate it via " +
  "`baselane graph .` (or `/graph regenerate`) whenever modules are added, removed, or moved.";

const GRAPHIFY_README = `# Graph adapter: graphify

## Setup

Install graphify (check the tool's own install docs for the current command, e.g.
\`npm install -g graphify\` or \`pipx install graphify\`), then verify it's on PATH:

\`\`\`
graphify --version
\`\`\`

## Usage

Run \`graphify build .\` to produce graphify's own graph — it tags edges as \`EXTRACTED\` or
\`INFERRED\`, going beyond this repo's zero-dep lexical scan. If graphify exposes an MCP server,
prefer querying it directly over reading its graph.json by hand.

A hook in this pack already guards on availability so it never fails silently when the tool
isn't installed:

\`\`\`
command -v graphify >/dev/null 2>&1 && graphify build . || echo "graphify not installed — see this file for setup"
\`\`\`

## How this maps to the baselane protocol

Same rule as the \`imports\` method: consult the graph before cross-module changes, not grep.
graphify's \`EXTRACTED\`/\`INFERRED\` split lines up with this repo's \`confidence\` field — treat
\`INFERRED\` edges as lower-confidence hints, not ground truth.
`;

const AIDER_README = `# Graph adapter: aider

## Setup

Install aider: \`pip install aider-chat\` (or \`pipx install aider-chat\`). There is no separate
graph-build step — aider computes its repo map automatically each session.

## Usage

Aider ranks and includes a "repo map" (signatures plus a relevance ordering) in its own context
automatically; there is nothing to run to regenerate it. When working through aider specifically,
trust its repo map for "what's relevant to this file" instead of asking it to grep.

## How this maps to the baselane protocol

Aider's repo map answers the same question this repo's \`imports\` method answers ("what's
connected to what"), just scoped to aider's own session rather than a checked-in graph.json. If
this repo also has an \`imports\`-method graph checked in, prefer that as the durable,
tool-agnostic source of truth; use aider's repo map as a live supplement while working in aider.
`;

const LSP_README = `# Graph adapter: lsp (Serena MCP)

## Setup

This adapter wires up [Serena](https://github.com/oraios/serena), an MCP server that gives an
agent LSP-grade semantic navigation (find-references, go-to-definition, symbol search) instead of
a static graph file.

A ready-to-merge MCP server entry is scaffolded at \`.baselane/mcp/serena.json\`. Merge its
contents into this repo's \`.mcp.json\` under the top-level \`"mcpServers"\` key — **never
overwrite an existing \`.mcp.json\`**; add the \`"serena"\` key alongside whatever servers are
already configured there. If there is no \`.mcp.json\` yet, the scaffolded file's contents can be
used as the entire \`.mcp.json\` body.

## Usage

Once merged and the MCP connection is available, prefer Serena's semantic tools (references,
definitions, symbol search) over lexical grep for any "what calls this" / "what implements this"
question — it understands the language's actual structure, not just import statements.

## How this maps to the baselane protocol

Same query-before-grep rule as the \`imports\` method, but answered with live semantic queries
instead of a generated graph.json. The two are complementary: \`imports\` is a durable, checked-in
snapshot; Serena is a live, more precise, but session-only index.
`;

const SERENA_MCP_SNIPPET =
  JSON.stringify(
    {
      mcpServers: {
        serena: {
          command: "uvx",
          args: ["--from", "git+https://github.com/oraios/serena", "serena-mcp-server"],
        },
      },
    },
    null,
    2,
  ) + "\n";

const SOURCEGRAPH_README = `# Graph adapter: sourcegraph

## Setup

Install the Sourcegraph CLI (\`src\`) — see https://sourcegraph.com/docs/cli — then point it at
your instance:

\`\`\`
src login <your-sourcegraph-endpoint>
\`\`\`

(or set \`SRC_ENDPOINT\` / \`SRC_ACCESS_TOKEN\` in the environment instead of an interactive login).

## Usage

Use \`src search\` for cross-repo code search, and \`src api\` (or the GraphQL API directly) to ask
"what references this symbol" across every repo the instance indexes — not just this one.

## How this maps to the baselane protocol

Same query-before-grep rule as the \`imports\` method, scoped to an entire Sourcegraph instance
rather than one checked-out repo. Reach for this adapter specifically when the question spans
multiple repos; use \`imports\` (or another local adapter) for single-repo questions.
`;

function graphCapabilities(pack: WorkflowPack, store: "org" | "repo"): Capability[] {
  return (pack.capabilities ?? []).filter((c) => c.type === "graph" && c.store === store && REAL_METHODS.has(c.method));
}

export function hasRepoGraphCapability(pack: WorkflowPack): boolean {
  return graphCapabilities(pack, "repo").length > 0;
}

export function hasOrgGraphCapability(pack: WorkflowPack): boolean {
  return graphCapabilities(pack, "org").length > 0;
}

/** Adds the /graph command + Stop-hook reminder (and, if configured, the graphify hook). */
export function withGraphScaffolding(pack: WorkflowPack): WorkflowPack {
  const hasGraphify = (pack.capabilities ?? []).some((c) => c.type === "graph" && c.method === "graphify");
  return {
    ...pack,
    commands: [...pack.commands, GRAPH_COMMAND],
    hooks: [...pack.hooks, GRAPH_STOP_HOOK, ...(hasGraphify ? [GRAPHIFY_HOOK] : [])],
  };
}

/** Files for one graph method, rooted at `baseDir` (`.baselane/graph` for repo, `graph` for bundle). */
function methodFiles(baseDir: string, method: string, isRepo: boolean): FileMap {
  switch (method) {
    case "imports":
      return { [`${baseDir}/README.md`]: GRAPH_README };
    case "graphify":
      return { [`${baseDir}/graphify/README.md`]: GRAPHIFY_README };
    case "aider":
      return { [`${baseDir}/aider/README.md`]: AIDER_README };
    case "lsp":
      // The MCP snippet is repo-local by nature (it merges into this repo's own .mcp.json), so
      // it's only rendered on the repo side, never into the laptop bundle.
      return {
        [`${baseDir}/lsp/README.md`]: LSP_README,
        ...(isRepo ? { ".baselane/mcp/serena.json": SERENA_MCP_SNIPPET } : {}),
      };
    case "sourcegraph":
      return { [`${baseDir}/sourcegraph/README.md`]: SOURCEGRAPH_README };
    default:
      return {};
  }
}

function renderGraphFilesFor(capabilities: Capability[], baseDir: string, isRepo: boolean): FileMap {
  const files: FileMap = {};
  for (const c of capabilities) Object.assign(files, methodFiles(baseDir, c.method, isRepo));
  return files;
}

/** `.baselane/graph/...` files, for every real-method repo-store graph capability the pack declares. */
export function renderRepoGraphFiles(pack: WorkflowPack): FileMap {
  return renderGraphFilesFor(graphCapabilities(pack, "repo"), ".baselane/graph", true);
}

/** `graph/...` files in the laptop bundle, for every real-method org-store graph capability. */
export function renderBundleGraphFiles(pack: WorkflowPack): FileMap {
  return renderGraphFilesFor(graphCapabilities(pack, "org"), "graph", false);
}
